import AsyncStorage from "@react-native-async-storage/async-storage";
import { create } from "zustand";
import { createJSONStorage, persist } from "zustand/middleware";
import { WeatherStoreType } from "../types/types";

export const weatherStore = create<
  WeatherStoreType,
  [["zustand/persist", unknown]]
>(
  persist(
    (set, _get) => ({
      weather: {
        latitude: 0,
        longitude: 0,
        generationtime_ms: 0,
        utc_offset_seconds: 0,
        timezone: "",
        timezone_abbreviation: "",
        elevation: 0,
        current_units: {
          time: "iso8601",
          interval: "seconds",
          temperature_2m: "",
          apparent_temperature: "",
          relative_humidity_2m: "%",
          is_day: "",
          weather_code: "wmo code",
          surface_pressure: "hPa",
          precipitation: "",
          rain: "",
          showers: "",
          snowfall: "",
          wind_speed_10m: "",
          wind_gusts_10m: "",
          wind_direction_10m: "°",
        },
        current: {
          time: "",
          interval: 0,
          temperature_2m: 0,
          relative_humidity_2m: 0,
          apparent_temperature: 0,
          is_day: 0,
          weather_code: 0,
          surface_pressure: 0,
          precipitation: 0,
          wind_speed_10m: 0,
          wind_direction_10m: 0,
          wind_gusts_10m: 0,
        },
        hourly_units: {
          time: "iso8601",
          dew_point_2m: "",
          precipitation_probability: "%",
          precipitation: "",
          visibility: "m",
          uv_index: "",
          temperature_2m: "",
          relative_humidity_2m: "%",
          apparent_temperature: "",
          weather_code: "wmo code",
          surface_pressure: "hPa",
          wind_speed_10m: "",
          wind_direction_10m: "°",
          wind_gusts_10m: "",
          soil_temperature_0cm: "",
          sunshine_duration: "s",
          direct_normal_irradiance: "W/m²",
        },
        hourly: {
          time: [],
          dew_point_2m: [],
          precipitation_probability: [],
          precipitation: [],
          visibility: [],
          uv_index: [],
          temperature_2m: [],
          relative_humidity_2m: [],
          apparent_temperature: [],
          weather_code: [],
          surface_pressure: [],
          wind_speed_10m: [],
          wind_direction_10m: [],
          wind_gusts_10m: [],
          soil_temperature_0cm: [],
          sunshine_duration: [],
          direct_normal_irradiance: [],
        },
        daily_units: {
          time: "iso8601",
          weather_code: "wmo code",
          temperature_2m_max: "",
          temperature_2m_min: "",
          precipitation_sum: "",
          precipitation_hours: "h",
          precipitation_probability_max: "%",
          sunrise: "iso8601",
          sunset: "iso8601",
          sunshine_duration: "s",
          daylight_duration: "s",
          uv_index_max: "",
          wind_speed_10m_max: "",
          wind_gusts_10m_max: "",
          shortwave_radiation_sum: "MJ/m²",
          dew_point_2m_mean: "",
          surface_pressure_mean: "hPa",
        },
        daily: {
          time: [],
          weather_code: [],
          temperature_2m_max: [],
          temperature_2m_min: [],
          precipitation_sum: [],
          precipitation_hours: [],
          precipitation_probability_max: [],
          sunrise: [],
          sunset: [],
          sunshine_duration: [],
          daylight_duration: [],
          uv_index_max: [],
          wind_speed_10m_max: [],
          wind_gusts_10m_max: [],
          shortwave_radiation_sum: [],
          dew_point_2m_mean: [],
          surface_pressure_mean: [],
        },
      },
      addWeather: (weatherData) =>
        set(() => ({
          weather: weatherData,
        })),
    }),
    {
      name: "weather-storage",
      storage: createJSONStorage(() => AsyncStorage),
    }
  )
);
